### ISSUE TITLE
Add optional tag

### ISSUE THREAD

**Issue by tzinckgraf** [dlo9/calibre-recipes#1]
It would be great to add tag as a user option.

I was also having an issue with max_articles.

I will submit a PR for a simple fix.

**Comment by mmagnus** [comment]
@tzinckgraf you can add tag in this version of the code https://github.com/mmagnus/Pocket-Plus-Calibre-Plugin

**Comment by dlo9** [comment]
Closing, since @mmagnus's version of the code has this fix and I'm not actively maintaining
